### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Sacristan** [rsense/atom-rsense#6]
[Enter steps to reproduce below:]
1. Open a Ruby on Rails model

**Atom Version**: 0.200.0
**System**: Mac OS X 10.9.5
**Thrown From**: [rsense](git://github.com/rsense/atom-rsense) package, v0.6.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: undefined is not a function
    at /Users/girts/.atom/packages/rsense/lib/rsense.coffee:54:32
    at atom-workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-view.js:97:22)
    at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:110:34)
    at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
    at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
    at TextEditorView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
    at TextEditorView.module.exports.TextEditorView.afterAttach (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-view.js:178:19)
```
### Commands

```
     -0:04.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
highlight-selected, v0.9.3
language-csharp, v0.5.0
rsense, v0.6.0
ruby-block, v0.3.3
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by Sacristan** [comment]
Any progress on this ?
