### ISSUE TITLE
I got some errors with rsense on Atom

### ISSUE THREAD

**Issue by ahrherrera** [rsense/atom-rsense#9]
On Windows 10 64-bit with Atom 1.13.1

```

Error starting rsense
autocomplete-ruby: exec error: Error: Command failed: C:/Ruby23-x64/bin/rsense start --port 47367 --path C:\Users\ahrhe\Documents\GitHub\facilitoclub
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/lib/rsense/client/runner.rb:112:in `start': uninitialized constant Spoon::FileActions (NameError)
Did you mean?  FileUtils
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/bin/rsense:12:in `<top (required)>'
	from C:/Ruby23-x64/bin/rsense:22:in `load'
	from C:/Ruby23-x64/bin/rsense:22:in `<main>'
```

**Comment by id-rams** [comment]
I have  got same issue 
win 10, 
atom 1.15.0
`C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/lib/rsense/client/runner.rb:112:in `start': uninitialized constant Spoon::FileActions (NameError)
Did you mean?  FileUtils
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/bin/rsense:12:in `<top (required)>'
        from C:/Ruby23-x64/bin/rsense:22:in `load'
        from C:/Ruby23-x64/bin/rsense:22:in `<main>'`

**Comment by chadwtaylor** [comment]
+1

**Comment by itggot-henrik-tholin** [comment]
+1

**Comment by lflores1961** [comment]
I have this problem
 $ apm install rsense
Installing rsense to /home/lflores/.atom/packages ✗
No available version compatible with the installed Atom version: 1.38.2
